version: 2

# Define the jobs for the current project.
jobs:
  build:

    # Specify the Xcode version to use.
    macos:
      xcode: "9.2.0"
    working_directory: ~/edx-app-ios
    environment:
      XCODE_WORKSPACE: edX.xcworkspace
      XCODE_SCHEME: edX
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pip install requests
            brew update
            brew upgrade openssl
            brew install ruby
            brew install imagemagick
            brew cleanup
            sudo gem install fastlane
            ./gradlew dependencies --stacktrace --info
      - run:
          name: Download app resources
          command: |
            git clone git@github.com:proversity-org/edx-app-ios-config.git --branch proversity/fia --single-branch ./deployment
            cp -R deployment/assets/app_icons/ Source/Resources/Images.xcassets/AppIcon.appiconset
            cp -R deployment/assets/app_icons/ Source/Resources/Icons
            cp -R deployment/assets/logos/ Source/Resources/Images
            cp -R deployment/assets/splash_screens/ Source/Resources/Splash
            cp -R deployment/assets/images/ Source/Resources/Images
            cp -R deployment/assets/iTunesArtwork@2x.png iTunesArtwork@2x.png
            cp -R deployment/assets/iTunesArtwork@2x.png Source/Resources/Images
            cp -R deployment/colors.json Source/Resources/Colors
            cp -R deployment/config_project.py config_project.py
            cp -R deployment/custom_config custom_config
            cp -R deployment/default_config/ default_config
            cp -R deployment/fastlane fastlane
            cp -R deployment/fonts.json Source/Resources/Fonts
            cp -R deployment/setup_certificates.py setup_certificates.py
      - run:
          name: Deploy to Testflight
          command: |
            python config_project.py "fia,FIATA,2.13.6,2.13,e96ba5e6-87e0-442c-bfbf-69d4b9fea807,547234fd-683a-4e79-9d2f-ba72a5cbc2a5"
            fastlane beta

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
