version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - run:
          name: Install  dependencies
          command: |
            sudo pip install requests
            brew update && brew upgrade openssl
            brew update && brew install ruby
            brew cask install fastlane
            brew install imagemagick
            brew cleanup
            sudo gem install fastlane
            ./gradlew dependencies --stacktrace --info
      - run:
          name: Clone config repo
          command: git clone git@github.com:proversity-org/edx-mobile-config.git --single-branch --branch no-branch ./deployment
      - run:
          name: Copy config files
          command: |
            cp -R deployment/iOS/assets/iTunesArtwork@2x.png iTunesArtwork@2x.png
            cp -R deployment/iOS/assets/app_icons/ Source/Resources/Icons
            cp -R deployment/iOS/assets/logos/ Source/Resources/Images
            cp -R deployment/iOS/assets/splash_screens/ Source/Resources/Splash
            cp -R deployment/iOS/assets/images/ Source/Resources/Images
            cp -R deployment/iOS/colors.json Source/Resources/Colors
            cp -R deployment/iOS/fonts.json Source/Resources/Fonts
            cp -R deployment/iOS/custom_config custom_config
            cp -R deployment/iOS/default_config default_config
            cp -R deployment/iOS/fastlane fastlane
            cp -R deployment/iOS/files/edX-Info.plist Source/edX-Info.plist
            cp -R deployment/iOS/files/edX.entitlements edX.entitlements
            cp -R deployment/iOS/files/project.pbxproj edX.xcodeproj/project.pbxproj
      - run:
          name: Deploy
          command: fastlane beta