version: 2

# Define the jobs for the current project.
jobs:
  build:

    # Specify the Xcode version to use.
    macos:
      xcode: "9.3.1"
    working_directory: ~/edx-app-ios
    environment:
      XCODE_WORKSPACE: edX.xcworkspace
      XCODE_SCHEME: edX
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v0.0.1-brew-cache-
      - run:
          name: Install Python dependencies
          command: sudo pip install requests
      - run:
          name: Install Brew dependencies
          command: |
            brew update
            brew upgrade openssl
            brew install ruby
            brew install imagemagick
            brew cleanup
      - run:
          name: Install Fastlane
          command: sudo gem install fastlane
      - run:
          name: Install Gradle dependencies
          command: ./gradlew dependencies --stacktrace --info
      - save_cache:
          key: v0.0.1-brew-cache-
          paths:
            - /usr/local/Homebrew
      - run:
          name: Setup app
          command: |
            git clone git@github.com:proversity-org/edx-app-ios-config.git --branch proversity/slp --single-branch --depth=1 ./deployment
            cp -R deployment/assets/app_icons/ Source/Resources/Images.xcassets/AppIcon.appiconset
            cp -R deployment/assets/app_icons/ Source/Resources/Icons
            cp -R deployment/assets/logos/ Source/Resources/Images
            cp -R deployment/assets/splash_screens/ Source/Resources/Splash
            cp -R deployment/assets/images/ Source/Resources/Images
            cp -R deployment/assets/iTunesArtwork@2x.png iTunesArtwork@2x.png
            cp -R deployment/assets/iTunesArtwork@2x.png Source/Resources/Images
            cp -R deployment/colors.json Source/Resources/Colors
            cp -R deployment/config_project.py config_project.py
            cp -R deployment/custom_config custom_config
            cp -R deployment/default_config/ default_config
            cp -R deployment/fastlane fastlane
            cp -R deployment/fonts.json Source/Resources/Fonts
            cp -R deployment/setup_certificates.py setup_certificates.py
      - run:
          name: Deploy to Testflight
          command: |
            python config_project.py "slp,SLP,2.15.2,2.15,1bc161c4-5fba-41dc-a68d-faa219e028f8,fd86de56-cc17-4499-8bf1-3e987c2dcbbf"
            fastlane screenshots
      - run:
          name: Save logs
          command: |
            mkdir -p /tmp/core_dumps
            cp -r /Users/distiller/Library/Logs/gym/edX-edX.log /tmp/core_dumps
            cp -r /Users/distiller/Library/Logs/snapshot/edX-edX.log /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
